openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description:  The library service

tags:
  - name: "Project"


paths:
  /projectDetail:
    get:
      summary: This is summary
      tags:
        - "Project"
      description: This is a description
      operationId:  getProjectDetail


      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetailDto'

components:
  schemas:
    ProjectDetailDto:
      description: Data transfer object for fetching project detail
      type: object
      properties:
        name:
          description: The name of web project
          type: string
        id:
          description: The numeric identifier of web project
          type: int

