# Shared properties for all environments...

port: 80
swaggerPath: "/swagger-ui:html"

production:
  server:
    url: "http://servername.com"
    name: "Some server name"

development:
  test: "Test"
  server:
    url: "http://localhost:80"
    name: "Development Tepsivo BE server"